# Generated by Django 6.0.3 on 2026-03-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_plan_campaign_document_contact_messagelog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='village',
            new_name='address',
        ),
    ]
